### ISSUE TITLE
Divine Sense

### ISSUE THREAD

**Issue by CaosFR** [gambit07/gambits-premades#37]
Hello,

I'm trying to use my paladin's divine perception but the ability has no effect.

I've watched the video and I'm not getting the expected result (nothing is actually happening). I have all the required modules. 
I get this warning on launch :

```
workflow.js:2480 midi-qol | called macro error in Perception divine [Paladin] Actor.tQxmf34Rd4i7B42h.Item.qWdYEa0heRQ722AG macro ItemMacro TypeError: Cannot read properties of undefined (reading 'value')
    at getTypeOrRace (eval at #executeScript (foundry.js:20082:16), <anonymous>:17:49)
    at eval (eval at #executeScript (foundry.js:20082:16), <anonymous>:22:22)
    at Array.forEach (<anonymous>)
    at AdvancedMacro.eval (eval at #executeScript (foundry.js:20082:16), <anonymous>:21:9)
    at #executeScript (foundry.js:20087:17)
    at AdvancedMacro.execute (foundry.js:20028:35)
    at AdvancedMacro.execute (main.js:40:20)
    at e.callMacro (workflow.js:2598:17)
    at e.callMacros (workflow.js:2478:21)
    at e.WorkflowState_RollFinished (workflow.js:1701:15)
    at async e.WorkflowState_RollFinished (workflow.js:65:17)
    at async e.performState (workflow.js:513:21)
```

However, it's not very clear to me. You mark in the example “if you don't want to use the vision5e setting” but in the object “Requires [..] Vision5e”. Does Vision5e need to be installed?
In all cases, with or without, the problem is the same. Vision5e's “divine perception” effect works well for your information.
There is also a load consumption called “ws850ODKlMg3lWN3”, I don't know what this corresponds to. Normally it should be 1 of “1 + @abilities.cha.mod” per long rest.

Foundry v12
DnD 3.3.1
Chromium 129
Gambit 0.5.68

**My system is in French**

**Comment by gambit07** [comment]
> Hello,
> 
> I'm trying to use "Divine Sense" but the ability has no effect.
> 
> I've watched the video and I'm not getting the expected result (nothing is actually happening). I have all the required modules. I get this warning on launch :
> 
> ```
> workflow.js:2480 midi-qol | called macro error in Perception divine [Paladin] Actor.tQxmf34Rd4i7B42h.Item.qWdYEa0heRQ722AG macro ItemMacro TypeError: Cannot read properties of undefined (reading 'value')
>     at getTypeOrRace (eval at #executeScript (foundry.js:20082:16), <anonymous>:17:49)
>     at eval (eval at #executeScript (foundry.js:20082:16), <anonymous>:22:22)
>     at Array.forEach (<anonymous>)
>     at AdvancedMacro.eval (eval at #executeScript (foundry.js:20082:16), <anonymous>:21:9)
>     at #executeScript (foundry.js:20087:17)
>     at AdvancedMacro.execute (foundry.js:20028:35)
>     at AdvancedMacro.execute (main.js:40:20)
>     at e.callMacro (workflow.js:2598:17)
>     at e.callMacros (workflow.js:2478:21)
>     at e.WorkflowState_RollFinished (workflow.js:1701:15)
>     at async e.WorkflowState_RollFinished (workflow.js:65:17)
>     at async e.performState (workflow.js:513:21)
> ```
> 
> However, it's not very clear to me. You mark in the example “if you don't want to use the vision5e setting” but in the object “Requires [..] Vision5e”. Does Vision5e need to be installed? In all cases, with or without, the problem is the same. Vision5e's “Divine Sense” effect works well for your information. There is also a resource consumption called “ws850ODKlMg3lWN3”, I don't know what this corresponds to. Normally it should be 1 of “1 + @abilities.cha.mod” per long rest.
> 
> resource consumption :
> 
> Vision5e : ![image](https://private-user-images.githubusercontent.com/37581932/380523089-9d75e596-2c09-4bf3-9de5-406830d76ac8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTEwNjMsIm5iZiI6MTczMDA5MDc2MywicGF0aCI6Ii8zNzU4MTkzMi8zODA1MjMwODktOWQ3NWU1OTYtMmMwOS00YmYzLTlkZTUtNDA2ODMwZDc2YWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA0NDYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4MmMxZDJkYjQzNTJhM2ZmMzNkMzZmMWQxNzg1OTQ3Y2M1YzI1ZTZjNjdjNTlmZmUyZGNlMTg5MmMxZmVlYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hokgiBUwas07c4b6cWgdZPPCyMbe7m47x_ZkVr6E-0k) ![image](https://private-user-images.githubusercontent.com/37581932/380523055-7b4dcc64-69c2-442d-a463-9f1969325a1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTEwNjMsIm5iZiI6MTczMDA5MDc2MywicGF0aCI6Ii8zNzU4MTkzMi8zODA1MjMwNTUtN2I0ZGNjNjQtNjljMi00NDJkLWE0NjMtOWYxOTY5MzI1YTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA0NDYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNDE3ZmJjMWEyMDhhZDJlMGNlOTkwODFjZWNhY2RkMjBiZjM5YTgzMjcxNjgxOTE1YmQ3MTBiMmJjNjRlMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2mNkBECpAbwLPlqw-Alqd9EwQYXg9yRwzp-YL0cbcnw) ![image](https://private-user-images.githubusercontent.com/37581932/380523159-f46d8a0b-0f90-4a1f-a4fe-e37090e800c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTEwNjMsIm5iZiI6MTczMDA5MDc2MywicGF0aCI6Ii8zNzU4MTkzMi8zODA1MjMxNTktZjQ2ZDhhMGItMGY5MC00YTFmLWE0ZmUtZTM3MDkwZTgwMGM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA0NDYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NjYzYjc4YjgyYTE2ZWUwNmIxMWYxNzBlMjAxYTRhODlkNTI4ZWNjNjc4MzliYjdiNjU1ZTFkZTJlYjVjMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QJbBIPzrhUWGbsYvyVj_6sIkeNIxRYXJmEFHCyiIfTk)
> 
> Gambit : ![image](https://private-user-images.githubusercontent.com/37581932/380523254-aba141c9-37d3-49ae-a21d-0b241496685b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTEwNjMsIm5iZiI6MTczMDA5MDc2MywicGF0aCI6Ii8zNzU4MTkzMi8zODA1MjMyNTQtYWJhMTQxYzktMzdkMy00OWFlLWEyMWQtMGIyNDE0OTY2ODViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA0NDYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZGFiZTFlNGJjZDc0ZTdmYzlmNjliMDQwMjJlOWYzNDY3N2FjYzk5ZGNiNGI4NjViYTNmZjE5ZjA2MGVhMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gSru0KZRd9OUsUwjwq2tgT7g99qpz4u37Xx_C_sk4uI) ![image](https://private-user-images.githubusercontent.com/37581932/380523022-49914909-1bc2-415e-ad23-5ec86f01db81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTEwNjMsIm5iZiI6MTczMDA5MDc2MywicGF0aCI6Ii8zNzU4MTkzMi8zODA1MjMwMjItNDk5MTQ5MDktMWJjMi00MTVlLWFkMjMtNWVjODZmMDFkYjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA0NDYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmOTg0YjA4ZDlhNWVlYWZjOGNlNTYzNjNhZDEwNTlmOWNiMTNlNjk4Mjc3OGZlZWZiNmFjNWU2ZjZkOGQxMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KM6QPxUsrk7-hXObJVJd5gxkRr0CrCnyboGPb1psKAY) ![image](https://private-user-images.githubusercontent.com/37581932/380523229-617cf9af-7946-4cc3-9bb9-7e09984a7890.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTEwNjMsIm5iZiI6MTczMDA5MDc2MywicGF0aCI6Ii8zNzU4MTkzMi8zODA1MjMyMjktNjE3Y2Y5YWYtNzk0Ni00Y2MzLTliYjktN2UwOTk4NGE3ODkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA0NDYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyODYwMDhlYzcwMGJiYzkwZjYzYzllNmYzZTNlYzhlMWNlMjQzYjUxY2M0NWY5MjNkYTQzNzNhYjIyMzlmZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SLXn0lIkUHJY-v8z5jFyQVAEvn6NrwsLrurwdIK39Zs)
> 
> Foundry v12 DnD 3.3.1 Chromium 129 Gambit 0.5.68
> 
> **My game system is in French** (same problem if a keep "Divine Sense" name)

I tested and am not seeing any issues with the automation currently. Try re-testing on a new scene with just the two actors you're trying to test. My best guess is an issue with an invalid token on the canvas of the scene that you're testing currently.

As far as vision5e, this automation enables vision5e's divine sense for a specific time duration on use and then disables it. That's what I was referring to in my note about not having it always active. If you just have the setting active in vision5e, your player will always have divine sense sight, so it kind of defeats the purpose of the divine sense feature being limited use. You can see how that plays out in the video below

https://github.com/user-attachments/assets/9764d9ef-2b34-49a1-99ef-4225057e0de7

**Comment by CaosFR** [comment]
I've tried it on a new stage and it works... Very strange, thanks for the tip I would never have thought it was related to the scene.
On some scenes I have a problem, other names... I can't explain it.
Thanks for the support :)
